name: DipSA CICD Workshop

# trigger
on: 
  push:
   branches:
    - 'v[0-9]+[0-9]+'


# Jobs in the workflow
jobs: 
  # jobs name
  Myworkflow-go-fortune: 
  # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps: 
    - name: Release GitHub Actions
      uses: technote-space/release-github-actions@v6
