name: DipSA CICD Workshop

# trigger
on: 
  push:
   branches:
    - 'v[0-9]+.[0-9]+'


# Jobs in the workflow
jobs: 
  # jobs name
  Myworkflow-go-fortune: 
  # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps: 
    - name: Echo Date
      run: echo "The current time and date in Github is $(date)"
    - name: Deploy to Railway
      uses: devtomio/action-railway@v1.1.4
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
    - name: Release GitHub Actions
      uses: planet-code/release-tag-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-branch-format: "v[0-9]+.[0-9]+"
        show-changelog: true
