name: DipSA CICD Workshop

# trigger
on: 
  push:
   branches:
    - 'v[0-9]+.[0-9]+'


# Jobs in the workflow
jobs: 
  # jobs name
  Myworkflow-go-fortune: 
    if: "!startsWith( github.event.head_commit.message, '#NORUN' )"
  # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps: 
    - name: Checkout the branch
      uses: actions/checkout@v3
    - name: Use Node 19
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{github.ref_name}}
        allowUpdates: true
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nMENG XIANZHU"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0265091E"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne1045766@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n<${{github.repositoryUrl}}>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\n<${{secrets.DEPLOY_URL_SECRET}}>"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{secrets.DEPLOY_URL_SECRET}}|Open Application>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK