name: DipSA CICD Workshop

# trigger
on: 
  push:
   branches:
    - 'v[0-9]+.[0-9]+'


# Jobs in the workflow
jobs: 
  # jobs name
  Myworkflow-go-fortune: 
    if: "!startsWith( github.event.head_commit.message, '#NORUN' )"
  # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps: 
    - name: Checkout the branch
      uses: actions/checkout@v3
    - name: Use Node 19
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{github.ref_name}}
        allowUpdates: true
    - name: ehco information about the context
      run: echo "Git URL to the repository - ${{github.repositoryUrl}}"
    - name: Get deployment URL
      id: deployment
      uses: dorshinar/get-deployment-url@master
      timeout-minutes: 5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run end-to-end tests
      run: npm run test:e2e
      env:
        deployment: ${{ steps.deployment.outputs.deployment }}