name: DipSA CICD Workshop

# trigger
on: 
  push:
   branches:
    - 'v[0-9]+.[0-9]+'


# Jobs in the workflow
jobs: 
  # jobs name
  Myworkflow-go-fortune: 
  # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps: 
    - name: Checkout the branch
      uses: actions/checkout@v3
    - name: Use Node 19
      uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{github.ref_name}}
        allowUpdates: true
